# These are supported funding model platforms

github: [nunomaduro,owenvoke,olivernybroe,octoper]
patreon: nunomaduro
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
